Asp.Net MVC_Managing Trucks/Truck/ViewModels/InvoiceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Truck.Core;

namespace Truck.ViewModels
{
    public class InvoiceViewModel
    {
        public int? Id { get; set; }
        public int AssignmentId { get; set; }
        public int AssignmentStatusId { get; set; }
        public int? StatusId { get; set; }
        public string Status { get; set; }
        public int AssignmentNumber { get; set; }
        [Required]
        [Display(Name ="Invoice #")]
        public int Number { get; set; }
        [Required]
        [Display(Name = "Work Order #")]
        public string WONumber { get; set; }
        [Required]
        [Display(Name = "Invoice Amount")]
        public decimal Amount { get; set; }
        [Display(Name = "Adjustment")]
        public decimal AdjustmentAmount { get; set; }
        [Display(Name = "Amount Payable")]
        public decimal PaidAmount { get; set; }
        [Display(Name = "Check Amount")]
        public decimal CheckAmount { get; set; }      
        [Required]
        [Display(Name ="Customer Name")]
        public string CustomerName { get; set; }
        public DateTime? Date { get; set; }
        [Display(Name ="Check Receive Date")]
        [DisplayFormat(DataFormatString="dd/MM/yyyy")]
        public DateTime? CheckDate { get; set; }
        [Display(Name ="Hold Reason")]
        public string HoldReason { get; set; }
        [Display(Name ="Check Number")]
        public string CheckNumber { get; set; }
        public int FilesCount { get; internal set; }
        public IList<AttachmentViewModel> Attachments { get; set; }
        public AdjustmentViewModel Adjustment { get; set; }
        public int WaitingDays { get; set; }
    }
}

Asp.Net MVC_Managing Trucks/Truck/Controllers/BaseController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Practices.Unity;
using Truck.Core;
using Truck.Data;
using Truck.Data.Repositories;
using Truck.Infrastructure;
using Truck.Infrastructure.Extensions;
using Truck.Infrastructure.Services;
using Truck.Models;
using Truck.Services;
using Truck.ViewModels;

namespace Truck.Controllers
{
    public class BaseController : Controller
    {
        public ApplicationUserManager UserManager => new ApplicationUserManager(new UserStore<ApplicationUser>(IdentityDb));
        public RoleManager<IdentityRole> RoleManager => new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(IdentityDb));
        [Dependency]
        public IMapper Mapper
        {
            get; set;
        }
        [Dependency]
        public ApplicationDbContext IdentityDb
        {
            get; set;
        }

        private TruckDbContext _dbContext;

        public TruckDbContext DbContext
        {
            get
            {
                if (_dbContext == null)
                    _dbContext = new TruckDbContext();
                return _dbContext;
            }
        }
        [Dependency]
        public IDbService<Attachment> AttachmentService { get; set; }

        [Dependency]
        public IUploadFileService UploadFileService { get; set; }
        public string UserId => User.Identity.GetUserId();
        public int CustomerId => User.IsInRole("admin")? 0 : IdentityDb.Users.Single(item => item.Id == UserId).CustomerId.Value;

       [HttpGet]
        public FileResult DownloadPdf(int id)
        {
            var file = AttachmentService.Find(id);
            //var vPath =GoogleDriveService.GetAsPdf(file.GoogleDriveId);
            return File(Server.MapPath(file.Path), "application/pdf", file.Name.Split('.')[0] + ".pdf");
        }
        
        //generate random password
        public string GeneratePassword(int totalLength)
        {
            const string valid = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            const string validSmallLetters = "abcdefghijklmnopqrstuvwxyz";
            const string validNumbers = "1234567890";
            const string validBigLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            const string validNonAlpha = "#*&^%$#@";
            var random = new Random();

            string password = string.Empty;
            var length = totalLength - 4;

            password += validBigLetters[random.Next(validBigLetters.Length)];
            password += validSmallLetters[random.Next(validSmallLetters.Length)];
            for (int i = 0; i < length; ++i)
                password += valid[random.Next(valid.Length)];
            password += validNumbers[random.Next(validNumbers.Length)];
            password += validNonAlpha[random.Next(validNonAlpha.Length)];

            return password;
        }

       
        //upload query of Excel template file
        protected string UploadFile(HttpPostedFileBase httpPostedFileBase,string fileName)
        {
            var dirPath = "~/Files/" + CustomerId + "/" + UserId;
            //create the directory if not exists
            var physPath = Server.MapPath(dirPath);
            if (!Directory.Exists(physPath))
                Directory.CreateDirectory(physPath);
            var filePath = dirPath + "/" + DateTime.Now.ToString("ddMMyyyyhhmmsstt") + fileName;
            httpPostedFileBase.SaveAs(Server.MapPath(filePath));
            return filePath;
        }
        //override JSon to return camel Case json
        protected override JsonResult Json(object data, string contentType, Encoding contentEncoding, JsonRequestBehavior behavior)
        {
            return new JsonDotNetResult
            {
                Data = data,
                ContentType = contentType,
                ContentEncoding = contentEncoding,
                JsonRequestBehavior = behavior
            };
        }
    }
}

Asp.Net MVC_Managing Trucks/Truck/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using Truck.Core;
using Truck.Data.Infrastructure;
using Truck.Infrastructure;
using Truck.Models;
using Truck.ViewModels;
using Truck.Services;

namespace Truck.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class InvoiceController : BaseController
    {
        private readonly IAssignmentService _assignmentService;
        private readonly IDbService<Invoice> _invoiceService;
        private readonly IDbService<InvoiceAttachment> _invoiceAttachmentService;
        private readonly IDbService<Attachment> _attachmentService;
        private readonly IDbService<Adjustment> _adjustmentService;
        private readonly IDbService<Customer> _customerService;
        private readonly IUnitOfWork _uow;

        public InvoiceController(IAssignmentService assignmentService,IDbService<Adjustment> adjustmentService, IDbService<Invoice> invoiceService,IDbService<InvoiceAttachment> invoiceAttachmentService, IDbService<Attachment> attachmentService, IDbService<Customer> customerService, IUnitOfWork uow)
        {
            _assignmentService = assignmentService;
            _invoiceService = invoiceService;
            _invoiceAttachmentService = invoiceAttachmentService;
            _attachmentService = attachmentService;
            _customerService = customerService;
            _adjustmentService = adjustmentService;
            _uow = uow;
        }
        
        public ActionResult Index(int? assignmentId)
        {
            if (assignmentId.HasValue)
            {
                ViewBag.AssignmentNumber = _assignmentService.Find(assignmentId.Value).Number;
                ViewBag.AssignmentId = assignmentId.Value;
            }
            ViewBag.Customers = _customerService.All.Select(item => new SelectListItem
            {
                Text = item.CustomerName,
                Value = item.Id.ToString()
            });
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> GetInvoices(BootGridRequest request)
        {
            var isAdmin = User.IsInRole("admin");
            if (isAdmin && !request.Params.ContainsKey("assignmentId"))
                return await SearchInvoices(request);
            int? assignmentId = null;
            if (request.Params != null && request.Params.Keys.Contains("assignmentId") && !string.IsNullOrEmpty(request.Params["assignmentId"]))
                assignmentId = int.Parse(request.Params["assignmentId"]);
            var invoicesVm = Mapper.Map<IEnumerable<InvoiceViewModel>>(_invoiceService.AllIncluding(item=>item.Assignment,item=>item.InvoiceStatus,item=>item.Assignment.AssignmentStatus).Where(item => (item.Assignment.CustomerId == CustomerId||isAdmin) && (!assignmentId.HasValue || item.AssignmentId == assignmentId.Value)));
            var response = new BootGridResponse<InvoiceViewModel>(request, invoicesVm);
            foreach (var item in response.Rows)
            {
                item.FilesCount = _invoiceAttachmentService.All.Count(ia=>ia.InvoiceId==item.Id);
            }
            return Json(response);
        }
     
        [HttpGet]
        public async Task<ActionResult> EditInvoice(int id)
        {
            var isAdmin = User.IsInRole("admin");
            var invoice = _invoiceService.AllIncluding(item=>item.Assignment,item=>item.InvoiceAttachments,item=>item.InvoiceAttachments.Select(e=>e.Attachment)).SingleOrDefault(item=>item.Id==id&& (isAdmin || item.Assignment.CustomerId == CustomerId));
            var invoiceVm = Mapper.Map<InvoiceViewModel>(invoice);
            //invoiceVm.Attachments =Mapper.Map<IEnumerable<AttachmentViewModel>>(invoice.InvoiceAttachments.Select(item=>item.Attachment));
            invoiceVm.Attachments = invoice.InvoiceAttachments.Select(item => new AttachmentViewModel
            {
                Id = item.Attachment.Id,
                Name = item.Attachment.Name.Substring(0, item.Attachment.Name.Length - 3) + "pdf",
                Path = item.Attachment.Path,//remove ~
                IsCheck=item.IsCheck
                
            }).ToList();
            if (isAdmin)
            {
                ViewBag.Statues = new List<SelectListItem>()
                {
                    new SelectListItem() {Value="3",Text = "On Hold" },
                    new SelectListItem() {Value="4",Text = "Originals Required" }
                };
                 return PartialView("AdminEditInvoice",invoiceVm);
            }
               
            return PartialView(invoiceVm);
        }

        [HttpPost]
        public async Task<JsonResult> EditInvoice(InvoiceViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(new { Error = "Complete all required fields" });
            if (model.Id.HasValue)
            {
                var isAdmin = User.IsInRole("admin");
                var invoice = _invoiceService.AllIncluding(item => item.Assignment,item=>item.Assignment.Customer,item=>item.Assignment.Invoices,item=>item.InvoiceAttachments,item=>item.InvoiceAttachments.Select(e=>e.Attachment)).SingleOrDefault(item => item.Id == model.Id.Value && (isAdmin || item.Assignment.CustomerId == CustomerId));
                if (invoice != null)
                {
                    var assignment = invoice.Assignment;
                    if (!isAdmin && assignment.StatusId != 1)
                        return Json(new { Error = "Cannot edit submitted or approved invoices" });
                    _uow.BeginTransaction();
                    invoice.Amount = model.Amount;
                    invoice.PaidAmount=invoice.Amount - (invoice.Amount * assignment.Customer.Rate/100);
                    invoice.CustomerName = model.CustomerName;
                    invoice.Number = model.Number;
                    invoice.WONumber = model.WONumber;
                    invoice.HoldReason = model.HoldReason;
                    Attachment attachment=null;
                    
                    //if check amount < paid amount and overpayment is null then create overpayment
                    decimal? adjustment = null;
                    if (isAdmin)
                    {
                        invoice.CheckAmount = model.CheckAmount;
                        invoice.CheckNumber = model.CheckNumber;
                        if (model.CheckDate != null)
                            invoice.CheckDate = model.CheckDate;
                        //upload check
                        
                        if (Request.Files.Count > 0 && Request.Files["check"] != null)
                        {
                            var ext = Request.Files["check"].FileName.Substring(Request.Files["check"].FileName.LastIndexOf(".", StringComparison.Ordinal)).ToLower();
                            var tempFileName = UploadFileService.UploadFile(Request.Files["check"]);
                            var invoiceCheck = invoice.InvoiceAttachments.Where(item=>item.IsCheck).FirstOrDefault();
                            if (invoiceCheck?.Attachment != null)
                            { 
                                invoiceCheck.Attachment.Path = "/PdfFiles/" + tempFileName + ".pdf";
                                invoiceCheck.Attachment.OrgFilePath = "/OrgFiles/" + tempFileName + ext;
                                invoiceCheck.Attachment.Name = Request.Form["Check_Name"];
                                _attachmentService.Update(invoiceCheck.Attachment);
                            }
                            else
                            {
                                invoiceCheck = new InvoiceAttachment
                                {
                                    IsCheck = true,
                                    Attachment = new Attachment
                                    {
                                        Path = "/PdfFiles/" + tempFileName+".pdf",
                                        OrgFilePath = "/OrgFiles/" + tempFileName + ext,
                                        Name = Request.Form["Check_Name"]
                                    }
                                };
                               
                                if (invoice.InvoiceAttachments == null)
                                    invoice.InvoiceAttachments = new List<InvoiceAttachment>();
                                invoice.InvoiceAttachments.Add(invoiceCheck);
                            }
                            attachment = invoiceCheck.Attachment;
                        }
                        if (model.CheckAmount >= 0 && !string.IsNullOrEmpty(model.CheckNumber) &&
                            model.CheckDate.HasValue)
                        {
                            if (model.CheckAmount == 0)
                                invoice.StatusId = 5;
                            else
                                invoice.StatusId = 2;
                            var oldAdjustment = _adjustmentService.FindBy(item=>item.OriginInvoiceId==invoice.Id).FirstOrDefault();
                            
                                if (oldAdjustment != null)
                                {
                                    oldAdjustment.Amount = invoice.CheckAmount - invoice.Amount;
                                    if (oldAdjustment.Amount == 0)
                                        _adjustmentService.Delete(oldAdjustment);
                                    else
                                        _adjustmentService.Update(oldAdjustment);
                                }
                                else
                                {
                                    if (invoice.CheckAmount != invoice.Amount)

Asp.Net MVC_Managing Trucks/Truck/Views/Invoice/AdminEditInvoice.cshtml
@model Truck.ViewModels.InvoiceViewModel
<style>
  #editModal   .modal-dialog {
  height: 97%;
  margin: 1% auto !important;
}

#editModal .modal-content {
height: 100%;
}
#editModal .modal-body {
      position: absolute;
    bottom: 0;
    top: 65px;
}
.tab-content,.tab-pane {
    height:100%;
}
</style>
<div class="" style="height:230px">
    @using (Html.BeginForm("EditInvoice", "Invoice", FormMethod.Post, new { id = "editInvoiceForm" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control", type = "number", required = "" } })
                </div>

                @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-1 nopadding" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", type = "number", required = "" } })
                </div>

                @Html.LabelFor(model => model.WONumber, htmlAttributes: new { @class = "control-label col-md-1 nopadding" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.WONumber, new { htmlAttributes = new { @class = "form-control", required = "" } })

                </div>

                @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-1 nopadding" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control", required = "" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PaidAmount, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.PaidAmount, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                </div>

                <label class="control-label col-md-1  nopadding">Upload check</label>
                <div class="col-md-2">
                    <input type="file" id="check" class="form-control" />
                </div>
                @Html.LabelFor(model => model.CheckNumber, htmlAttributes: new { @class = "control-label col-md-1 nopadding" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CheckNumber, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.LabelFor(model => model.CheckAmount, htmlAttributes: new { @class = "control-label col-md-1 nopadding" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CheckAmount, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CheckDate, htmlAttributes: new { @class = "control-label col-md-1" })
                <div class="col-md-2">
                    @Html.EditorFor(model => model.CheckDate, new { htmlAttributes = new { @class = "form-control date" } })
                </div>
                
                <label class="control-label col-md-1">Hold</label>
                <div class="col-md-2">
                    @Html.DropDownListFor(model => model.StatusId, ViewBag.Statues as IEnumerable<SelectListItem>, "", new {@class = "form-control"})
                </div>
               
                @Html.LabelFor(model => model.HoldReason, htmlAttributes: new { @class = "control-label col-md-1 holdReason" })
                <div class="col-md-2 holdReason">
                    @Html.TextAreaFor(model => model.HoldReason, new { @class = "form-control holdReason",required= "required" } )
                </div>
                <label id="adjustmentAmount" class="h5 text-danger col-md-push-1 col-md-5 bold" style="display:none">Adjustment amount = <span></span></label>
            </div>
            <div class="">
                <button class="btn" type="button" data-dismiss="modal" aria-hidden="true">Close</button>
                @if (Model.StatusId != 2)
                {

                    <button type="button" class="btn btn-primary" disabled="disabled" id="btnSave" onclick="saveInvoice()"><i class="fa fa-save"></i> Save</button>
                }
            </div>
        </div>
    }
</div>

<div class="attachments-images-container" >

    <ul class="nav nav-tabs">
        @for (var i = 0; i < Model.Attachments.Count(); i++)
        {
            var title = "Attachment " + (i + 1);
            if (Model.Attachments.ElementAt(i).IsCheck)
            {
                title = "Check";
            }

            <li @if (i == 0) { <text> class="active" </text>   }><a data-toggle="tab" href="@("#att" + Model.Attachments.ElementAt(i).Id)">@title</a></li>
        }
    </ul>
    <div class="tab-content">
        @for (var i = 0; i < Model.Attachments.Count(); i++)
        {
            <div @if (i == 0) { <text> class="tab-pane fade in active" </text>    } else { <text> class="tab-pane fade" </text>   }
                 id="@("att" + Model.Attachments.ElementAt(i).Id)">
                <iframe src="@Model.Attachments.ElementAt(i).Path"
                         @if (Model.Attachments.ElementAt(i).IsCheck)
                         {
                             <text> class="pdfFrame check"</text>
                         }
                         else
                         {
                             <text> class="pdfFrame"</text>
                         }


                        ></iframe>
            </div>
        }
    </div>

</div>

<script type="text/javascript">
    $(function () {
        $("#editModal").keypress(function (e) {
            if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
                $("#editModal #btnSave").trigger("click");
                e.stopPropagation();
                return false;
            } else {
                return true;
            }
        });
        $("#editInvoiceForm .form-control").change(function() {
            $("#editInvoiceForm #btnSave").removeAttr("disabled");
        });
        $(".holdReason").hide();
        $("#StatusId").change(function() {
            if ($(this).val() === "3")
                $(".holdReason").show();
            else
                $(".holdReason").hide();
        });
        //$(".attachments-images-container iframe").each(function() {
        //    var $this = $(this);
        //    $.get($this.attr("data-path")).done(function (result) {
        //        $this.attr("src", result);
        //        $this.show();
        //    });
        //});
        $("#editInvoiceForm #CheckDate").datetimepicker({
            format: 'm/d/Y',
            dateFormat: 'm/d/Y',
            timepicker: false
        });
        if ($("#editInvoiceForm #CheckDate").val() != null)
            $("#editInvoiceForm #CheckDate").val($("#editInvoiceForm #CheckDate").val().split(' ')[0]);
    })
    function saveInvoice() {
        if (!$("#editInvoiceForm").valid())
            return;
        if ($("#StatusId").val() !== "") {
            var result = confirm("New Assignemt(s) will be created");
            if (result === false)
                return;
        }
            
        var data = new window.FormData();
        var formFields = $("form#editInvoiceForm").serializeArray();
        $(formFields).each(function () {
            if (this.name === "StatusId") {
                if (this.value !== "")
                    data.append(this.name, this.value);
            }
            else
                data.append(this.name, this.value);
        });

        data.append("check", $("#check")[0].files[0]);
        //add file name
        data.append("check_name", $("#check").val().replace(/^.*\\/, ""));

        $.ajax({
            type: 'post',
            url: "@Url.Action("EditInvoice", "Invoice")",
            data: data,
        processData: false,
        contentType: false,
        beforeSend: function () {
            $("#btnSave").find('i').removeClass("fa-save").addClass("fa-spinner fa-spin");
        },
        complete: function () {
            $("#btnSave").find('i').removeClass("fa-spinner").removeClass("fa-spin").addClass("fa-save");
        },
        success: function(result) {
            if (result.error === undefined) {
                if (typeof (invoicesSaved) == "function")
                    invoicesSaved(result);
                $("#id").val(result.id);
                $("#check").val("");
                if (result.adjustment != null) {
                    $("#adjustmentAmount").show().find("span").text("$ " + result.adjustment);
                } else {
                    $("#editModal").modal("hide");
                    $("#adjustmentAmount").hide();
                }
                $("#invoices-grid").bootgrid('reload');
                $("#editInvoiceForm #btnSave").attr("disabled", "disabled");
             
                if (result.checkId != null && result.path != null) {
                    var checkIFrame = $("iframe.pdfFrame.check");
                    if (checkIFrame.length === 0) {
                        var iframe = "<iframe src='" + result.path + "' class='pdfFrame' ></iframe>";
                        $(".attachments-images-container ul").append("<li><a data-toggle='tab' href='#att" + result.checkId + "'>Check</a></li>");
                        $(".attachments-images-container .tab-content").append("<div class='tab-pane fade' id='att" + result.checkId + "'>" + iframe + "</div>");

                    } else
                        checkIFrame.attr("src", result.path);
                }
            } else if (result.error != undefined) {
                toastr.error(result.error);
            }
        }
    });
    }
</script>

Asp.Net MVC_Managing Trucks/Truck/Views/Invoice/EditInvoice.cshtml
@model Truck.ViewModels.InvoiceViewModel

@using (Html.BeginForm("EditInvoice","Invoice",FormMethod.Post,new {id= "editInvoiceForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control",type="number",required="" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", type = "number", required = "" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.WONumber, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.WONumber, new { htmlAttributes = new { @class = "form-control", required = "" } })

            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control", required = "" } })
            
            </div>
        </div>

    </div>
}

Asp.Net MVC_Managing Trucks/Truck/Views/Invoice/InvoiceFiles.cshtml
@model IEnumerable<Truck.ViewModels.AttachmentViewModel>

<table class="table table-bordered table-striped">
@foreach (var item in Model) {
    <tr>
        <td>
            <a href="#" onclick="downloadFile('@Url.Action("DownloadPdf", "Base")/@item.Id')">@item.Name.Split('.')[0]</a>
        </td>
        @if (User.IsInRole("user"))
        {
            <td class="text-center">
                <a href="#" onclick="deleteFile(@item.InvoiceId,@item.Id,this)"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        }
       
    </tr>
}
</table>