Asp.Net MVC_Managing Trucks/Truck/ViewModels/AssignmentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Truck.ViewModels
{
    public class AssignmentViewModel
    {
        public int? Id { get; set; }
        public int Number { get; set; }
        public string ChildLetter { get; set; }
        [Required]
        public decimal Fuel { get; set; }
        public decimal Funded { get; set; }
        public decimal Total { get; set; }
        [Display(Name="Total Payable")]
        public decimal TotalPayable { get; set; }
        public decimal Fee { get; set; }
        public decimal? Adjustment { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        [Required]
        [Display(Name = "Signature")]
        public string Signature { get; set; }
        public DateTime Date { get; set; }
        public int StatusId { get; set; }
        public string Status { get; set; }
        [Display(Name="Invoice Count")]
        public int InvoicesCount { get; set; }
        public string Name { get; set; }
        public IList<InvoiceViewModel> Invoices { get; set; }
        [Display(Name="Is Funded")]
        public bool IsFunded { get; set; }
        public string ReturnReason { get; set; }
    }
}

Asp.Net MVC_Managing Trucks/Truck/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using Truck.Core;
using Truck.Data.Infrastructure;
using Truck.Infrastructure;
using Truck.Infrastructure.Services;
using Truck.Models;
using Truck.ViewModels;
using Truck.Services;

namespace Truck.Controllers
{
    [Authorize(Roles ="admin,user")]
    public class AssignmentController : BaseController
    {
        private readonly IAssignmentService _assignmentService;
        private readonly IDbService<Invoice> _invoiceService;
        private readonly IDbService<Customer> _customerService;
        private readonly IDbService<AssignmentStatus> _assignmentStatusService;
        private readonly IDbService<Adjustment> _overpaymentService;
        private readonly IDbService<InvoiceAttachment> _invoiceAttachmentService;
        private readonly IDbService<Attachment> _attachmentService;
        private readonly IUploadFileService _uploadFileService;
        private readonly IUnitOfWork _uow;

        public AssignmentController(IAssignmentService assignmentService, IDbService<Invoice> invoiceService, IDbService<AssignmentStatus> assignmentStatusService, IUnitOfWork uow, IDbService<Customer> customerService, IUploadFileService uploadFileService, IDbService<Adjustment> overpaymentService, IDbService<InvoiceAttachment> invoiceAttachmentService, IDbService<Attachment> attachmentService)
        {
            _assignmentService = assignmentService;
            _invoiceService = invoiceService;
            _assignmentStatusService = assignmentStatusService;
            _customerService = customerService;
            _overpaymentService = overpaymentService;
            _invoiceAttachmentService = invoiceAttachmentService;
            _attachmentService = attachmentService;
            _uploadFileService = uploadFileService;
            _uow = uow;
        }
        // GET: UserViewModels
        public ActionResult Index()
        {
            ViewBag.StatusId = Request.QueryString["StatusId"];
            ViewBag.CustomerId = Request.QueryString["CustomerId"];
            if (string.IsNullOrEmpty(Request.QueryString["StatusId"]))
            {
                var statuses = _assignmentStatusService.All;
                if (User.IsInRole("admin"))
                    statuses = statuses.Where(item=>item.Id > 2);//admin should not see new or returned assignments, he see them when they are submitted
                ViewBag.AssignmentStatuses = statuses.Select(item => new SelectListItem
                {
                    Value = item.Id.ToString(),
                    Text = item.Status
                });
            }
            else
                ViewBag.StatusName = _assignmentStatusService.Find(int.Parse(Request.QueryString["StatusId"]))?.Status;
            if (!string.IsNullOrEmpty(Request.QueryString["CustomerId"]))
                ViewBag.CustomerName = _customerService.Find(int.Parse(Request.QueryString["CustomerId"]))?.CustomerName;
            return View();
        }
        [HttpPost]
        public JsonResult GetAssignments(BootGridRequest request)
        {
            int? statusId = null;
            if (request.Params != null)
            {
                if (request.Params.Keys.Contains("StatusId")&& !string.IsNullOrEmpty(request.Params["StatusId"]))
                    statusId = int.Parse(request.Params["StatusId"]);
            }
            
            var isAdmin = User.IsInRole("admin");
            var assignmentsVm = Mapper.Map<IEnumerable<AssignmentViewModel>>(_assignmentService.AllIncluding(item=>item.AssignmentStatus).Where(item=>(item.CustomerId==CustomerId || isAdmin) && (!statusId.HasValue||item.StatusId==statusId.Value)&&((!isAdmin||item.StatusId>2))));
            var response = new BootGridResponse<AssignmentViewModel>(request, assignmentsVm);
            foreach (var item in response.Rows)
            {
                item.InvoicesCount = _invoiceService.All.Count(i=>i.AssignmentId==item.Id);
                item.Adjustment = _overpaymentService.FindBy(e => e.OriginInvoice.AssignmentId == item.Id && e.StatusId == 1).Sum(e => (decimal?)e.Amount);
            }
            return Json(response);
        }
        
        [HttpGet]
        public async Task<ActionResult> Edit(int? id)
        {
            
            var assignmentVm = new AssignmentViewModel();
            var user = UserManager.FindByName(User.Identity.Name);
                if (user != null)
                    assignmentVm.Name = user.FirstName + " " + user.LastName;
var isAdmin = User.IsInRole("admin");
            if (id.HasValue)
            {
                var assignment =
                    _assignmentService.AllIncluding(item => item.Invoices,item=>item.Invoices.Select(e=>e.InvoiceAttachments), item => item.Invoices.Select(e => e.InvoiceStatus), item=>item.Invoices.Select(e=>e.InvoiceAttachments.Select(a=>a.Attachment)))
                        .FirstOrDefault(item => item.Id == id && (isAdmin || item.CustomerId == CustomerId));
                Mapper.Map(assignment,assignmentVm);
                assignmentVm.InvoicesCount = assignment.Invoices.Count;
                if (!isAdmin)
                {
                    //load everything in assignment
                    assignmentVm.Invoices = Mapper.Map<List<InvoiceViewModel>>(assignment.Invoices);
                    foreach (var invoice in assignmentVm.Invoices)
                    {
                        invoice.Attachments =
                            assignment.Invoices.Find(item => item.Id == invoice.Id)
                                .InvoiceAttachments.Select(item => item.Attachment)
                                .Select(item => new AttachmentViewModel
                                {
                                    Id = item.Id,
                                    Name = item.Name,
                                    Path = item.Path
                                }).ToList();
                    }
                }

                ViewBag.Title = "Edit Assignment # " + assignmentVm.Number;
                if (isAdmin)
                {
                    //get previous overpaid amount
                    var adjustment =
                        _overpaymentService.FindBy(
                            item => item.CustomerId == assignment.CustomerId && item.StatusId == 1).Sum(item => (decimal?)item.Amount);
                    if (adjustment.HasValue && adjustment != 0)
                        ViewBag.Adjustment = adjustment;
                    return View("AdminEditAssignment",assignmentVm);
                }
                    
            }
            else
            {
                assignmentVm.CustomerName = _customerService.Find(CustomerId).CustomerName;
				var assignmentsForCustomer = _assignmentService.FindBy(item => item.CustomerId == CustomerId);
				assignmentVm.Number = (assignmentsForCustomer.Any()?assignmentsForCustomer.Max(item => item.Number):0) + 1;
                assignmentVm.Invoices = new List<InvoiceViewModel>() {new InvoiceViewModel {Id = 0} };
                ViewBag.Title = "Create Assignment";
            }
            if(!isAdmin)
                ViewBag.CustomerRate = _customerService.Find(CustomerId).Rate/100;
            return View(assignmentVm);
        }

        [HttpPost]
        public JsonResult Edit(AssignmentViewModel model)
        {
            var isAdmin = User.IsInRole("admin");
            ModelState.Remove(isAdmin ? "Signature" : "Funded");
            if (!ModelState.IsValid)
                return Json(new {Error = "Complete required fields."}, JsonRequestBehavior.AllowGet);

            if (model.Id.HasValue)
            {
                var assignment =
                    _assignmentService.AllIncluding(item => item.Invoices)
                        .FirstOrDefault(item => item.Id == model.Id.Value && (isAdmin || item.CustomerId == CustomerId));

                if (assignment.StatusId > 2 && !isAdmin)
                    return Json(new {Error = "Cannot edit submitted or funded assignments"});
                if (assignment.StatusId >= 4 && isAdmin)
                    return Json(new {Error = "Cannot edit closed or funded assignments"});
                if (assignment.Fuel != model.Fuel)
                {
                    assignment.Fuel = model.Fuel;
                    _assignmentService.Recaculate(assignment);
                }
                if (isAdmin)
                {
                    if (model.IsFunded)
                    {
                        assignment.StatusId = 4;
                    }
                }
                else
                {
                    assignment.Signature = model.Signature;
                    //update invoices
                    //remove deleted invoices
                    var editedInvoicesIds = model.Invoices.Where(item => item.Id.HasValue).Select(item => item.Id);
                    var deleteInvoicesIds =
                        _invoiceService.FindBy(
                            item => item.AssignmentId == model.Id && !editedInvoicesIds.Contains(item.Id))
                            .Select(item => item.Id);
                    _invoiceService.Delete(deleteInvoicesIds.ToArray());
                    var customerRate = _customerService.Find(CustomerId).Rate / 100;
                    foreach (var invoiceModel in model.Invoices)
                    {
                        var invoiceEntity =
                            _invoiceService.AllIncluding(item => item.InvoiceAttachments)
                                .SingleOrDefault(item => item.Id == invoiceModel.Id);
                        if (invoiceEntity != null)
                        {

Asp.Net MVC_Managing Trucks/Truck/Views/Assignment/Index.cshtml
<div class="page">
    <h3 class="title">
        @if (ViewBag.StatusName != null)
        {
            @ViewBag.StatusName
        }
        Assignments
        @if (ViewBag.CustomerName != null)
        {
            <text> Of <b>@ViewBag.CustomerName</b></text>
        }
    </h3>
@if (ViewBag.StatusId == null)
{
    <div class="row">
        <label class="control-label col-md-2">Assignment Status</label>
        <div class="col-md-3">
            @Html.DropDownList("StatusId", ViewBag.AssignmentStatuses as IEnumerable<SelectListItem>, "", new { @class = "form-control" })
        </div>
    </div>
}
  

    <table id="assignments-grid" class="table table-condensed table-hover table-striped">
        <thead>
            <tr>
                <th data-column-id="id" data-type="numeric" data-visible="false" data-identifier="true" data-selection="true" selection="true">id</th>
                <th data-column-id="number" data-width="150" data-formatter="assignmentNumber">Assignment #</th>
                <th data-column-id="total" data-width="70" data-formatter="decimal">Total</th>
                <th data-column-id="fee" data-width="70" data-formatter="decimal">Fee</th>
                <th data-column-id="fuel" data-width="70"  data-formatter="decimal">Fuel</th>
                <th data-column-id="funded" data-width="80" data-formatter="decimal">Funded</th>
                <th data-column-id="adjustment" data-width="80" data-formatter="decimal">Adjustment</th>
                <th data-column-id="totalPayable" data-width="100" title="Total Payable" data-formatter="decimal">Total Payable</th>
                <th data-column-id="date" data-formatter="date" data-width="100">Date</th>
                <th data-column-id="status" data-width="100">Status</th>
                @if (User.IsInRole("admin"))
                {
                    <th data-formatter="review" data-width="80"></th>
                }
                else
                {
                  
                        <th data-column-id="returnReason" data-formatter="returned"  data-width="50"></th>
                  
                    <th data-formatter="invoices-link" data-align="center" class="center" data-width="70" headerCssClass="center" headerAlign="center" data-type="numeric">Invoices</th>
                    <th data-formatter="submit" data-width="80"></th>
                    <th data-column-id="commands" data-formatter="commands" data-sortable="false" data-width="70"></th>
                }
                
            </tr>
        </thead>
      
    </table>

    <div id="editModal" class="modal fade" tabindex="-1" role="dialog">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close pull-right" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 class="pull-left" id="title">Edit Assignment</h3>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <button class="btn btn-primary" id="btnSave" onclick="saveAssignment()">Save</button>
                </div>
            </div>
        </div>

    </div>

    <div class="modal fade" id="deleteModal" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Are you sure want to delete this assignment?</p>
                    <div>
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="btnConfirmDelete" onclick="processDeleteAssignment()">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="submitModal" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Are you sure want to submit this assignment?</p>
                    <div>
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="btnConfirmSubmit" onclick="processSubmitAssignment()">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="approveModal" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-body">
                    <p class="title">Are you sure want to approve this assignment?</p>
                    <div>
                        <button type="button" class="btn btn-default" data-dismiss="modal" id="btnApproveSubmit" onclick="processApproveAssignment()">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="returnReasonModal" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
              
                <div class="modal-body">
                    <p id="return-reason"></p>
                    <hr/>
                    <div>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        var currentAssignmentId = null;
        var assignmentsGrid = null;
        var operation = null;
        $(function () {
            $("#StatusId").change(function () {
                assignmentsGrid.bootgrid("reload");
            });
            assignmentsGrid = $("#assignments-grid").bootgrid({
                ajax: true,
                url: "@Url.Action("GetAssignments", "Assignment")",
                columnSettings: true,
                sorting: true,
                post: function () {
                    return { Params: { StatusId: $("#StatusId").val() || '@ViewBag.StatusId' } };
                },
                templates: {
                    header: bootGrid.getHeaderWithNew('@User.IsInRole("admin")' === "True" ? "" : "<a class='command-new btn btn-info pull-left' href='@Url.Action("Edit", "Assignment")'><i class='fa fa-plus'></i> New</a>")
                },
                formatters:
            {
                "assignmentNumber":
                function (column, row) {
                    return row.number + row.childLetter;
                },
                "commands":function (column, row) {
                    if (row.statusId <=2 || ('@User.IsInRole("admin")' === "True" && row.statusId === 4))
                        return bootGrid.getEditDeleteCommand(row.id);
                },
                "invoices-link":
                function (column, row) {
                    if (row.invoicesCount === 0)
                        row.invoicesCount = "";
                    return "<a href='@Url.Action("Index", "Invoice")?AssignmentId=" + row.id + "' class='badge'>" + row.invoicesCount + "</a>";
                },
                "submit":

                function (column, row) {
                    if (row.statusId === 1 || row.statusId === 2)
                        return "<button type='button' class='btn btn-success btn-sm' onclick='submitAssignment(" + row.id + ")'>Submit</button>";
                },
                "approve":
                function (column, row) {
                    if (row.statusId === 2)
                        return "<button type='button' class='btn btn-success btn-sm' onclick='approveAssignment(" + row.id + ")'>Approve</button>";
                    if (row.statusId === 3)
                        return "<button type='button' class='btn btn-success btn-sm' onclick='unApproveAssignment(" + row.id + ")'>UnApprove</button>";
                },
                "review":
                function (column, row) {
                    return "<button type='button' class='btn btn-success btn-sm' onclick='editAssignment(" + row.id + ")'>Review</button>";
                },
                "returned":
                function (column, row) {
                    if (row.status === "Returned")
                        return "<a style='color:red;cursor:pointer' ><i onclick='showReturnReason(\"" + row.returnReason + "\")' class='fa fa-envelope'></i></a>";
                },
                "date": function (column, row) {
                    if(row.date!=null)
                        return moment(row.date).format('MM/DD/YYYY');
                    }
            }
            }).
    on("loaded.rs.jquery.bootgrid", function () {
        assignmentsGrid.find(".command-edit").off().on("click", function () {
            var id = $(this).attr("data-row-id");
            editAssignment(id);
            return false;
        }).end().find(".command-delete").off().on("click", function () {
            var id = $(this).attr("data-row-id");
            deleteAssignment(id);

        });
    });


        });
  //acions
            function editAssignment(id) {
                window.location = "@Url.Action("Edit","Assignment")/" + id;
            }

            function deleteAssignment(id) {
                currentAssignmentId = id;
                $("#deleteModal").modal("show");
            }
        function saveAssignment() {
            if (!$("#editForm").valid())
                return;
            $.post('@Url.Action("Edit", "Assignment")', $("#editForm").serialize()).done(function (result) {
                if (result.error === undefined) {
                    $("#id").val(result.id);
                    $("#editModal").modal("hide");
                    assignmentsGrid.bootgrid('reload');

                } else if (result.error != undefined) {
                    toastr.error(result.error);
                }

            });
        }

        function submitAssignment(id) {
            currentAssignmentId = id;
            $("#submitModal").modal("show");
        }

        function approveAssignment(id) {
            currentAssignmentId = id;
            operation = "approve";
            $("#approveModal .title").text("Are you sure want to approve this assignment?");
            $("#approveModal").modal("show");
        }
        function unApproveAssignment(id) {
            currentAssignmentId = id;
            operation = "unapprove";
            $("#approveModal .title").text("Are you sure want to unapprove this assignment?");
            $("#approveModal").modal("show");
        }
        function processDeleteAssignment() {
            $.post('@Url.Action("Delete", "Assignment")' + "/" + currentAssignmentId).done(function (result) {
                if (result.done === 1) {
                    assignmentsGrid.bootgrid('reload');
                } else {
                    toastr.error(result.error);
                }
            });
        }

        function processSubmitAssignment() {
            $.post('@Url.Action("SubmitAssignment", "Assignment")' + "/" + currentAssignmentId).done(function (result) {
                if (result.done === 1) {
                    toastr.success("Assignment submitted successfully");
                    assignmentsGrid.bootgrid('reload');
                } else {
                    toastr.error(result.error);
                }
            });
        }

        function processApproveAssignment() {
            var url = "@Url.Action("ApproveAssignment", "Assignment")";
            var msg = "Assignment approved successfully";
            if (operation === "unapprove") {
                url = "@Url.Action("UnApproveAssignment", "Assignment")";
                msg = "Assignment unapproved successfully";
            }
            $.post(url + "/" + currentAssignmentId).done(function (result) {
                if (result.done === 1) {
                    toastr.success(msg);
                    assignmentsGrid.bootgrid('reload');
                } else {
                    toastr.error(result.error);
                }
            });
        }
        function showReturnReason(reason) {
            $("#returnReasonModal #return-reason").text(reason);
            $("#returnReasonModal").modal("show");
        }
    </script>
}