Asp.Net MVC_Managing Trucks/Truck/Controllers/Admin/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using Truck.Core;
using Truck.Data.Infrastructure;
using Truck.Infrastructure;
using Truck.Models;
using Truck.ViewModels;
using Truck.Services;
using Truck.ViewModels;

namespace Truck.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class UserManagementController : BaseController
    {
        private readonly IDbService<Customer> _customerService;

        public UserManagementController(IDbService<Customer> customerService)
        {
            _customerService = customerService;
        }

        // GET: UserViewModels
        public ActionResult Index()
        {
            return PartialView();
        }

        public JsonResult GetUsers(BootGridRequest request)
        {
            var usersVm = Mapper.Map<IEnumerable<UserViewModel>>(UserManager.Users.Include(item => item.Customer));
            return Json(new BootGridResponse<UserViewModel>(request, usersVm));
        }

        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            ViewBag.Customers = _customerService.All.Select(item => new SelectListItem
            {
                Text = item.CustomerName,
                Value = item.Id.ToString()
            });
            if (string.IsNullOrEmpty(id))
                return PartialView(new UserViewModel());
            var user = await UserManager.FindByIdAsync(id);
            return PartialView(Mapper.Map<UserViewModel>(user));
        }

        [HttpPost]
        public async Task<JsonResult> Edit(UserViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return Json(new {Error = "Complete all required fields"});
                if (string.IsNullOrEmpty(model.Id))
                {
                    //create user
                    var user = Mapper.Map<ApplicationUser>(model);
                    user.Id = Guid.NewGuid().ToString();
                    var randomPassword = GeneratePassword(8);
                    var result = await UserManager.CreateAsync(user, randomPassword);
                    if (result.Succeeded)
                    {
                        await UserManager.AddToRoleAsync(user.Id, "user");
                        //send email
                        var currentUser = UserManager.Users.SingleOrDefault(item => item.Id == UserId);

                        string msg = GetRegisterUsertEmailMsg();
                        msg = msg.Replace("@username", model.FirstName);
                        msg = msg.Replace("@byusername", currentUser?.FirstName + " " + currentUser?.LastName);
                        msg = msg.Replace("@email", model.Email);
                        msg = msg.Replace("@password", randomPassword);
                        msg = msg.Replace("@loginlink",
                            ConfigurationManager.AppSettings["SiteAddress"] + "/Account/Login");
                        msg = msg.Replace("@siteaddress", ConfigurationManager.AppSettings["SiteAddress"]);
                        MailService.SendMail(model.Email, "Truck System User Details", msg);
                        return Json(new {Done = 1});
                    }
                    return Json(new {Error = "Cannot create user, please try again later."});
                }
                else
                {
                    var user = await IdentityDb.Users.SingleOrDefaultAsync(item => item.Id == model.Id);
                    if (user != null)
                    {

                        user.FirstName = model.FirstName;
                        user.LastName = model.LastName;
                        user.CustomerId = model.CustomerId;
                        user.Email = model.Email;
                        user.PhoneNumber = model.PhoneNumber;
                        IdentityDb.SaveChanges();
                        return Json(new {Done = 1});
                    }
                    return Json(new {Error = "User not exist."});
                }
            }
            catch (Exception exp)
            {
                return null;
            }

        }

        [HttpPost]
        public async Task<JsonResult> Delete(string id)
        {
            var result = await UserManager.DeleteAsync(await UserManager.FindByIdAsync(id));
            if (result.Succeeded)
                return Json(new {Done = 1});
            return Json(new {Error = "Cannot delete this user."});
        }

        private string GetRegisterUsertEmailMsg()
        {
            return @"<div>
    <center>
        <h3>Truck System</h3>
        <hr />
    </center>
    <br />
    <p>
        Hi <b>@username</b>,
    </p>
    <p>
        You have been added to the Truck System by <b>@byusername</b>.
    </p>
    <p>
        Your username is <b>@email</b>
    </p>
    <p>
        Your password is <b>@password</b>
    </p>
    <p>Click the bellow link to login</p>
    <p>
        <a href='@loginlink'>@loginlink</a>
    </p>

    <p>
        Regards,
    </p>
    <p>
        Truck System
      </p>
      <p>
          <a href = '@siteaddress' > @siteaddress </a>
       </p>
   </div>";
        }
    }
}

Asp.Net MVC_Managing Trucks/Truck/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using Microsoft.AspNet.Identity;
using Truck.Core;
using Truck.Data.Infrastructure;
using Truck.Infrastructure;
using Truck.Models;
using Truck.ViewModels;
using Truck.Services;

namespace Truck.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class InvoiceController : BaseController
    {
        private readonly IAssignmentService _assignmentService;
        private readonly IDbService<Invoice> _invoiceService;
        private readonly IDbService<InvoiceAttachment> _invoiceAttachmentService;
        private readonly IDbService<Attachment> _attachmentService;
        private readonly IDbService<Adjustment> _adjustmentService;
        private readonly IDbService<Customer> _customerService;
        private readonly IUnitOfWork _uow;

        public InvoiceController(IAssignmentService assignmentService,IDbService<Adjustment> adjustmentService, IDbService<Invoice> invoiceService,IDbService<InvoiceAttachment> invoiceAttachmentService, IDbService<Attachment> attachmentService, IDbService<Customer> customerService, IUnitOfWork uow)
        {
            _assignmentService = assignmentService;
            _invoiceService = invoiceService;
            _invoiceAttachmentService = invoiceAttachmentService;
            _attachmentService = attachmentService;
            _customerService = customerService;
            _adjustmentService = adjustmentService;
            _uow = uow;
        }
        
        public ActionResult Index(int? assignmentId)
        {
            if (assignmentId.HasValue)
            {
                ViewBag.AssignmentNumber = _assignmentService.Find(assignmentId.Value).Number;
                ViewBag.AssignmentId = assignmentId.Value;
            }
            ViewBag.Customers = _customerService.All.Select(item => new SelectListItem
            {
                Text = item.CustomerName,
                Value = item.Id.ToString()
            });
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> GetInvoices(BootGridRequest request)
        {
            var isAdmin = User.IsInRole("admin");
            if (isAdmin && !request.Params.ContainsKey("assignmentId"))
                return await SearchInvoices(request);
            int? assignmentId = null;
            if (request.Params != null && request.Params.Keys.Contains("assignmentId") && !string.IsNullOrEmpty(request.Params["assignmentId"]))
                assignmentId = int.Parse(request.Params["assignmentId"]);
            var invoicesVm = Mapper.Map<IEnumerable<InvoiceViewModel>>(_invoiceService.AllIncluding(item=>item.Assignment,item=>item.InvoiceStatus,item=>item.Assignment.AssignmentStatus).Where(item => (item.Assignment.CustomerId == CustomerId||isAdmin) && (!assignmentId.HasValue || item.AssignmentId == assignmentId.Value)));
            var response = new BootGridResponse<InvoiceViewModel>(request, invoicesVm);
            foreach (var item in response.Rows)
            {
                item.FilesCount = _invoiceAttachmentService.All.Count(ia=>ia.InvoiceId==item.Id);
            }
            return Json(response);
        }
     
        [HttpGet]
        public async Task<ActionResult> EditInvoice(int id)
        {
            var isAdmin = User.IsInRole("admin");
            var invoice = _invoiceService.AllIncluding(item=>item.Assignment,item=>item.InvoiceAttachments,item=>item.InvoiceAttachments.Select(e=>e.Attachment)).SingleOrDefault(item=>item.Id==id&& (isAdmin || item.Assignment.CustomerId == CustomerId));
            var invoiceVm = Mapper.Map<InvoiceViewModel>(invoice);
            //invoiceVm.Attachments =Mapper.Map<IEnumerable<AttachmentViewModel>>(invoice.InvoiceAttachments.Select(item=>item.Attachment));
            invoiceVm.Attachments = invoice.InvoiceAttachments.Select(item => new AttachmentViewModel
            {
                Id = item.Attachment.Id,
                Name = item.Attachment.Name.Substring(0, item.Attachment.Name.Length - 3) + "pdf",
                Path = item.Attachment.Path,//remove ~
                IsCheck=item.IsCheck
                
            }).ToList();
            if (isAdmin)
            {
                ViewBag.Statues = new List<SelectListItem>()
                {
                    new SelectListItem() {Value="3",Text = "On Hold" },
                    new SelectListItem() {Value="4",Text = "Originals Required" }
                };
                 return PartialView("AdminEditInvoice",invoiceVm);
            }
               
            return PartialView(invoiceVm);
        }

        [HttpPost]
        public async Task<JsonResult> EditInvoice(InvoiceViewModel model)
        {
            if (!ModelState.IsValid)
                return Json(new { Error = "Complete all required fields" });
            if (model.Id.HasValue)
            {
                var isAdmin = User.IsInRole("admin");
                var invoice = _invoiceService.AllIncluding(item => item.Assignment,item=>item.Assignment.Customer,item=>item.Assignment.Invoices,item=>item.InvoiceAttachments,item=>item.InvoiceAttachments.Select(e=>e.Attachment)).SingleOrDefault(item => item.Id == model.Id.Value && (isAdmin || item.Assignment.CustomerId == CustomerId));
                if (invoice != null)
                {
                    var assignment = invoice.Assignment;
                    if (!isAdmin && assignment.StatusId != 1)
                        return Json(new { Error = "Cannot edit submitted or approved invoices" });
                    _uow.BeginTransaction();
                    invoice.Amount = model.Amount;
                    invoice.PaidAmount=invoice.Amount - (invoice.Amount * assignment.Customer.Rate/100);
                    invoice.CustomerName = model.CustomerName;
                    invoice.Number = model.Number;
                    invoice.WONumber = model.WONumber;
                    invoice.HoldReason = model.HoldReason;
                    Attachment attachment=null;
                    
                    //if check amount < paid amount and overpayment is null then create overpayment
                    decimal? adjustment = null;
                    if (isAdmin)
                    {
                        invoice.CheckAmount = model.CheckAmount;
                        invoice.CheckNumber = model.CheckNumber;
                        if (model.CheckDate != null)
                            invoice.CheckDate = model.CheckDate;
                        //upload check
                        
                        if (Request.Files.Count > 0 && Request.Files["check"] != null)
                        {
                            var ext = Request.Files["check"].FileName.Substring(Request.Files["check"].FileName.LastIndexOf(".", StringComparison.Ordinal)).ToLower();
                            var tempFileName = UploadFileService.UploadFile(Request.Files["check"]);
                            var invoiceCheck = invoice.InvoiceAttachments.Where(item=>item.IsCheck).FirstOrDefault();
                            if (invoiceCheck?.Attachment != null)
                            { 
                                invoiceCheck.Attachment.Path = "/PdfFiles/" + tempFileName + ".pdf";
                                invoiceCheck.Attachment.OrgFilePath = "/OrgFiles/" + tempFileName + ext;
                                invoiceCheck.Attachment.Name = Request.Form["Check_Name"];
                                _attachmentService.Update(invoiceCheck.Attachment);
                            }
                            else
                            {
                                invoiceCheck = new InvoiceAttachment
                                {
                                    IsCheck = true,
                                    Attachment = new Attachment
                                    {
                                        Path = "/PdfFiles/" + tempFileName+".pdf",
                                        OrgFilePath = "/OrgFiles/" + tempFileName + ext,
                                        Name = Request.Form["Check_Name"]
                                    }
                                };
                               
                                if (invoice.InvoiceAttachments == null)
                                    invoice.InvoiceAttachments = new List<InvoiceAttachment>();
                                invoice.InvoiceAttachments.Add(invoiceCheck);
                            }
                            attachment = invoiceCheck.Attachment;
                        }
                        if (model.CheckAmount >= 0 && !string.IsNullOrEmpty(model.CheckNumber) &&
                            model.CheckDate.HasValue)
                        {
                            if (model.CheckAmount == 0)
                                invoice.StatusId = 5;
                            else
                                invoice.StatusId = 2;
                            var oldAdjustment = _adjustmentService.FindBy(item=>item.OriginInvoiceId==invoice.Id).FirstOrDefault();
                            
                                if (oldAdjustment != null)
                                {
                                    oldAdjustment.Amount = invoice.CheckAmount - invoice.Amount;
                                    if (oldAdjustment.Amount == 0)
                                        _adjustmentService.Delete(oldAdjustment);
                                    else
                                        _adjustmentService.Update(oldAdjustment);
                                }
                                else
                                {
                                    if (invoice.CheckAmount != invoice.Amount)

Asp.Net MVC_Managing Trucks/Truck/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Truck.Core;
using Truck.Data.Infrastructure;
using Truck.Infrastructure;
using Truck.Services;
using Truck.ViewModels;

namespace Truck.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class ReportController : BaseController
    {
        private readonly IDbService<Assignment> _assignmentService;
        private readonly IDbService<Invoice> _invoiceService;
        private readonly IDbService<InvoiceStatus> _invoiceStatusService;
        private readonly IDbService<Customer> _customerService;
        private readonly IDbService<AssignmentStatus> _assignmentStatusService;
        private readonly IDbService<InvoiceAttachment> _invoiceAttachmentService;
        public ReportController(IDbService<Assignment> assignmentService, IDbService<Invoice> invoiceService, IDbService<AssignmentStatus> assignmentStatusService, IDbService<Customer> customerService, IDbService<InvoiceAttachment> invoiceAttachmentService,IDbService<InvoiceStatus> invoiceStatusService)
        {
            _assignmentService = assignmentService;
            _invoiceService = invoiceService;
            _assignmentStatusService = assignmentStatusService;
            _customerService = customerService;
            _invoiceAttachmentService = invoiceAttachmentService;
            _invoiceStatusService= invoiceStatusService;
        }

        public ActionResult PaidUnpaidInvoices(string status)
        {
            ViewBag.StatusId = status == "paid" ? 2 : 1;
            ViewBag.Customers =_customerService.All.Select(item=>new SelectListItem {Value=item.Id.ToString(),Text=item.CustomerName});
            ViewBag.InvoiceStatuses = _invoiceStatusService.All.Select(item=>new SelectListItem {Value=item.Id.ToString(),Text=item.Status});;
            return View();
        }
    }
}

Asp.Net MVC_Managing Trucks/Truck/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Truck - System</title>
    @Styles.Render("~/css/main")
    @Scripts.Render("~/bundles/modernizr")
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'/>
    <!-- lato font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css' />
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>

    <!-- navbar -->
    <header class="navbar navbar-inverse" role="banner">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" id="menu-toggler">
                <span class="sr-only">Toggle navigation</span>
                <span class="fa fa-bar"></span>
                <span class="fa fa-bar"></span>
                <span class="fa fa-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">
                <img src="~/img/logo.png" alt="logo" />
            </a>
        </div>
        <ul class="nav navbar-nav pull-right hidden-xs">
           
            <li class="notification-dropdown hidden-xs hidden-sm">
            
            </li>
          
            <li class="dropdown">
                <a href="#" class="dropdown-toggle hidden-xs hidden-sm" data-toggle="dropdown">
                    @User.Identity.Name
                 
                </a>
              
            </li>
         
            <li class="settings hidden-xs hidden-sm">
                <a href="@Url.Action("LogOff","Account")" role="button">
                    <i class="fa fa-share"></i>
                </a>
            </li>
        </ul>
    </header>
    <!-- end navbar -->
    <!-- sidebar -->
    <div id="sidebar-nav">
        <ul id="dashboard-menu">
            @if (User.IsInRole("admin"))
            {
            <li class="active">
                <a class="dropdown-toggle" href="@Url.Action("Index","CustomerManagement")">
                    <i class="fa fa-group"></i>
                    <span>Customer Management</span>
                </a>

            </li>
                @*<li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "UserManagement")">
                        <i class="fa fa-user"></i>
                        <span>User Management</span>
                    </a>

                </li>*@
                <li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "Assignment")">
                        <i class="fa fa-envelope"></i>
                        <span>Assignments</span>
                    </a>
                </li>
            }
           
            @if (User.IsInRole("user"))
            {
                @*<li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "Assignment")?StatusId=4">
                        <i class="fa fa-envelope"></i>
                        <span>Funded Assignments</span>
                    </a>
                </li>
                <li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "Assignment")?StatusId=1">
                        <i class="fa fa-envelope"></i>
                        <span>New Assignments</span>
                    </a>
                </li>
                <li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "Assignment")?StatusId=2">
                        <i class="fa fa-envelope"></i>
                        <span>Returned Assignments</span>
                    </a>
                </li>*@
                <li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Index", "Assignment")">
                        <i class="fa fa-envelope"></i>
                        <span>Assignments</span>
                    </a>
                </li>
                @*<li class="active">
                    <a class="dropdown-toggle" href="@Url.Action("Edit","Assignment")">
                        <i class="fa fa-group"></i>
                        <span>New Assignment</span>
                    </a>

                </li>*@

            }
            <li class="active">
                <a class="dropdown-toggle" href="@Url.Action("Index", "Invoice")">
                    <i class="fa fa-list"></i>
                    <span>Invoices</span>
                </a>

            </li>
            @*<li class="active">
                <a class="dropdown-toggle" href="@Url.Action("PaidUnpaidInvoices", "Report")?status=paid">
                    <i class="fa fa-dollar"></i>
                    <span>Paid Invoices</span>
                </a>

            </li>
            <li class="active">
                <a class="dropdown-toggle" href="@Url.Action("PaidUnpaidInvoices","Report")?status=unpaid">
                    <i class="fa fa-question"></i>
                    <span>UnPaid Invoices</span>
                </a>

            </li>*@
            @*<li>
                <a class="dropdown-toggle">
                    <i class="fa fa-list"></i>
                    <span>Reports</span>
                    <span class="fa arrow"></span>
                </a>
                   
                <ul class="nav nav-second-level collapse in" aria-expanded="true" style="">
                   
                </ul>
               
            </li>*@
           
        </ul>
    </div>
    <!-- end sidebar -->
    <!-- main container -->
    <div class="content">
       
        @RenderBody()
    </div>



    @Scripts.Render("~/bundles/jquery") 
    <script src="~/assets/js/jquery.bootgrid.js"></script>
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/main")
        @RenderSection("scripts", required: false)
    <script type="text/javascript">
            //$(function () {

            //    // jQuery Knobs
            //    $(".knob").knob();



            //    // jQuery UI Sliders
            //    $(".slider-sample1").slider({
            //        value: 100,
            //        min: 1,
            //        max: 500
            //    });
            //    $(".slider-sample2").slider({
            //        range: "min",
            //        value: 130,
            //        min: 1,
            //        max: 500
            //    });
            //    $(".slider-sample3").slider({
            //        range: true,
            //        min: 0,
            //        max: 500,
            //        values: [ 40, 170 ],
            //    });



            //    // jQuery Flot Chart
            //    var visits = [[1, 50], [2, 40], [3, 45], [4, 23],[5, 55],[6, 65],[7, 61],[8, 70],[9, 65],[10, 75],[11, 57],[12, 59]];
            //    var visitors = [[1, 25], [2, 50], [3, 23], [4, 48],[5, 38],[6, 40],[7, 47],[8, 55],[9, 43],[10,50],[11,47],[12, 39]];

            //    var plot = $.plot($("#statsChart"),
            //        [ { data: visits, label: "Signups"},
            //         { data: visitors, label: "Visits" }], {
            //            series: {
            //                lines: { show: true,
            //                        lineWidth: 1,
            //                        fill: true,
            //                        fillColor: { colors: [ { opacity: 0.1 }, { opacity: 0.13 } ] }
            //                     },
            //                points: { show: true,
            //                         lineWidth: 2,
            //                         radius: 3
            //                     },
            //                shadowSize: 0,
            //                stack: true
            //            },
            //            grid: { hoverable: true,
            //                   clickable: true,
            //                   tickColor: "#f9f9f9",
            //                   borderWidth: 0
            //                },
            //            legend: {
            //                    // show: false
            //                    labelBoxBorderColor: "#fff"
            //                },
            //            colors: ["#a7b5c5", "#30a0eb"],
            //            xaxis: {
            //                ticks: [[1, "JAN"], [2, "FEB"], [3, "MAR"], [4,"APR"], [5,"MAY"], [6,"JUN"],
            //                       [7,"JUL"], [8,"AUG"], [9,"SEP"], [10,"OCT"], [11,"NOV"], [12,"DEC"]],
            //                font: {
            //                    size: 12,
            //                    family: "Open Sans, Arial",
            //                    variant: "small-caps",
            //                    color: "#697695"
            //                }
            //            },
            //            yaxis: {
            //                ticks:3,
            //                tickDecimals: 0,
            //                font: {size:12, color: "#9da3a9"}
            //            }
            //         });

            //    function showTooltip(x, y, contents) {
            //        $('<div id="tooltip">' + contents + '</div>').css( {
            //            position: 'absolute',
            //            display: 'none',
            //            top: y - 30,
            //            left: x - 50,
            //            color: "#fff",
            //            padding: '2px 5px',
            //            'border-radius': '6px',
            //            'background-color': '#000',
            //            opacity: 0.80
            //        }).appendTo("body").fadeIn(200);
            //    }

            //    var previousPoint = null;
            //    $("#statsChart").bind("plothover", function (event, pos, item) {
            //        if (item) {
            //            if (previousPoint != item.dataIndex) {
            //                previousPoint = item.dataIndex;

            //                $("#tooltip").remove();
            //                var x = item.datapoint[0].toFixed(0),
            //                    y = item.datapoint[1].toFixed(0);

            //                var month = item.series.xaxis.ticks[item.dataIndex].label;

            //                showTooltip(item.pageX, item.pageY,
            //                            item.series.label + " of " + month + ": " + y);
            //            }
            //        }
            //        else {
            //            $("#tooltip").remove();
            //            previousPoint = null;
            //        }
            //    });
            //});
        </script>
    </body>
    </html>